# Generated by Django 5.2.9 on 2026-09-17 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nomi')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Nomi')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('image', models.ImageField(blank=True, help_text="Ixtiyoriy — rasm qo'shilmagan bo'lsa placeholder ko'rsatiladi.", null=True, upload_to='items/%Y/%m/%d/', verbose_name='Rasm')),
                ('location_name', models.CharField(max_length=200, verbose_name='Manzil')),
                ('contact', models.CharField(help_text='Masalan: @username yoki +998901234567', max_length=255, verbose_name="Bog'lanish (Telegram / telefon)")),
                ('status', models.CharField(choices=[('available', 'Bepul'), ('taken', 'Topshirilgan')], default='available', max_length=20, verbose_name='Holat')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='items.category', verbose_name='Kategoriya')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL, verbose_name='Egasi')),
            ],
            options={
                'verbose_name': 'Buyum',
                'verbose_name_plural': 'Buyumlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
